### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "kodom@ali.com",
    "password": "kodom1212121"
}
###


### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName": "Halum",
    "lastName": "Halum",
    "email": "halum@ali.com",
    "password": "halum1212121"
}
###