### Create a Roadmap
POST http://localhost:3000/roadmaps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM4N2YzZGRiLTkxNzQtNDZlYS1hNDhjLWU3YmRlYTY2NmQ2OCIsImlhdCI6MTc3ODE3OTU2MCwiZXhwIjoxNzc4Nzg0MzYwfQ.wf8HXNLBUCVlAgZEjqJpQIQSKHX5ieKSZVzXW60SK9M
Content-Type: application/json

{
    "title": "Mastering TypeORM",
    "description": "A complete guide to learning database relationships."
}

### Get my roadmaps
GET http://localhost:3000/roadmaps/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM4N2YzZGRiLTkxNzQtNDZlYS1hNDhjLWU3YmRlYTY2NmQ2OCIsImlhdCI6MTc3ODE3OTU2MCwiZXhwIjoxNzc4Nzg0MzYwfQ.wf8HXNLBUCVlAgZEjqJpQIQSKHX5ieKSZVzXW60SK9M
