### Get users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmZGU4YTNlLTI0ZDgtNGNjNC1hNmFlLTM2NDMxNGZmMDc0OSIsImlhdCI6MTc3ODE3MDE1NiwiZXhwIjoxNzc4Nzc0OTU2fQ.ZygzefYE_tJEOzjDx_bq55DxfsWQWeufZDtYPUiLjNI
###


### Post user
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Farhan",
    "lastName": "Elias",
    "email": "farhan@farhan1122com",
    "password": "farhan1212121"
}
###




### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "farhan@farhan.com",
    "password": "farhan1212121"
}
###
