### Get users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjMmI3ZDg5LTIzOTUtNDIxMy05NjczLTVkMjk4NjY1Njg5NSIsImlhdCI6MTc3ODEwNTA1NywiZXhwIjoxNzc4NzA5ODU3fQ.AGVcqWtcOiYLApYHntZ_FjA7YzUVuT7k-7utBpvY3GI
###


### Post user
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Farhan",
    "lastName": "Elias",
    "email": "farhan@farhan.com",
    "password": "farhan1212121"
}
###




### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "farhan@farhan.com",
    "password": "farhan1212121"
}
###
